# v2
[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npm run db:push && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
