export default function Terms() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <h1
        className="font-display font-black text-3xl text-court-white mb-2"
        style={{ letterSpacing: "0.06em" }}
      >
        TERMS OF SERVICE
      </h1>
      <p className="text-net-grey text-sm mb-10">Effective May 2026 · Hevini Sporting</p>

      <div className="space-y-10 text-net-grey text-sm leading-relaxed">
        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            1. Acceptance
          </h2>
          <p>
            By accessing or using 10IS ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These terms apply to all visitors, users, and others who access 10IS.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            2. Description of Service
          </h2>
          <p className="mb-3">
            10IS is an AI-powered tennis string recommendation engine operated by Hevini Sporting. The Service provides:
          </p>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li>Personalised string setup recommendations based on your racket, playstyle, and physical profile.</li>
            <li>A searchable database of tennis rackets.</li>
            <li>A stringer locator tool.</li>
            <li>An AI chat assistant (Club tier only).</li>
          </ul>
          <p className="mt-3">
            Recommendations are generated by AI and are for informational purposes only. They do not constitute professional sports science or medical advice. Always consult a qualified stringer or coach before making equipment changes, particularly if you have an injury.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            3. Accounts
          </h2>
          <p className="mb-3">
            You must provide a valid email address to create an account. You are responsible for maintaining the confidentiality of your password. You may not share your account or use another person's account without permission.
          </p>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or attempt to circumvent the tier system.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            4. Paid Tiers
          </h2>
          <ul className="list-disc list-inside space-y-2 ml-2">
            <li>
              <span className="text-court-white font-medium">Free</span> — 1 recommendation, racket database access, stringer search preview. No payment required.
            </li>
            <li>
              <span className="text-court-white font-medium">Pro ($4.99 one-time)</span> — Unlimited recommendations, full stringer search, saved history and restringing reminders. Charged once via Stripe.
            </li>
            <li>
              <span className="text-court-white font-medium">Club ($1.99/month)</span> — Everything in Pro plus AI chat assistant and multi-profile support. Billed monthly via Stripe. Cancel anytime from your Account page or by contacting us.
            </li>
          </ul>
          <p className="mt-3">
            Prices are in USD and may be subject to applicable taxes.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            5. Refunds
          </h2>
          <ul className="list-disc list-inside space-y-1.5 ml-2">
            <li><span className="text-court-white font-medium">Pro (one-time)</span> — All sales are final. We do not offer refunds on one-time purchases.</li>
            <li><span className="text-court-white font-medium">Club (subscription)</span> — You may cancel at any time. Cancellation takes effect at the end of the current billing period. No partial refunds are issued for unused time.</li>
          </ul>
          <p className="mt-3">
            If you believe you were charged in error, contact us at{" "}
            <a href="mailto:contact@hevini.com" className="text-hevini-red hover:underline">
              contact@hevini.com
            </a>{" "}
            within 7 days and we will review your case.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            6. Intellectual Property
          </h2>
          <p>
            All content, branding, and software on 10IS — including the Hevini and 10IS trademarks, logos, and recommendation output — are owned by Hevini Sporting or its licensors. You may not reproduce, distribute, or create derivative works without written permission.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            7. Disclaimer of Warranties
          </h2>
          <p>
            The Service is provided "as is" without warranties of any kind. We do not guarantee that recommendations will be accurate, complete, or suitable for your specific situation. Use of the Service is at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            8. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, Hevini Sporting shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including equipment damage or personal injury resulting from following a recommendation.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            9. Governing Law
          </h2>
          <p>
            These terms are governed by the laws of the State of Maryland, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Maryland.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            10. Changes to Terms
          </h2>
          <p>
            We may update these terms from time to time. We will notify registered users by email of material changes. Continued use of the Service after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-court-white font-bold text-base mb-3 uppercase" style={{ letterSpacing: "0.08em" }}>
            11. Contact
          </h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a href="mailto:contact@hevini.com" className="text-hevini-red hover:underline">
              contact@hevini.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
